# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  firebase-deploy: azdevs/firebase-deploy@1.0.0
jobs:
  build:
    docker:
      - image: 'circleci/node:10-browsers'
    steps:
      - checkout
      - restore_cache:
          key: 'v1-yarn-{{ checksum "yarn.lock" }}'
      - run: yarn install
      - save_cache:
          key: 'v1-yarn-{{ checksum "yarn.lock" }}'
          paths:
            - ./node_modules
      - run: yarn test
      - run: yarn build
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - dist
            - firebase.json
            - .firebaserc
            - firestore.rules
            - firestore.indexes.json
            - functions
  deploy:
    docker:
      - image: 'circleci/node:10'
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - firebase-deploy/deploy:
          token: $FIREBASE_TOKEN
          alias: staging
workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build