# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  firebase-deploy: azdevs/firebase-deploy@1.0.0
jobs:

  test-job:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout

      # Cache to enable faster future jobs
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Run tests
      - run: yarn test
  build:
    docker:
      - image: 'circleci/node:10'
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - dist
            - firebase.json
            - .firebaserc
            - firestore.rules
            - firestore.indexes.json
            - functions
  deploy:
    docker:
      - image: 'circleci/node:10'
    steps:
      - attach_workspace:
          at: ~/repo
      - firebase-deploy/deploy:
          token: $FIREBASE_TOKEN
          alias: staging
workflows:
  build-and-deploy:
    jobs:
      - deploy:
          requires:
            - test-job
            - build